import {Appearance} from 'react-native';

const colorScheme = !Appearance.getColorScheme();
const isLight = true;

export const STYLES = {
  Color: {
    primary: '#00DF9A',
    lightPrimary: '#d5ffea',
    secondary: '#0492AF',
    secondaryLight: '#02b0cc',
    smoothSecondary: '#e5fafd',
    first: '#313F41',
    lightFirst: '#4b595b',
    second: '#6A7678',
    third: '#94A0A2',
    fourth: '#009A94',
    light: isLight ? '#fff' : '#181818',
    firstBg: '#f8f9f9',
    secondBg: '#eaf1f1',
    thirdBg: '#dbdbdb',
    firstBorder: '#ddebeb',
    secondBorder: '#ebebeb',
    inputBg: '#f4f7f8',
    milkyWhite: '#dde9eb',
    milkyWhite2: '#FFF9E8',
    smoothWhite: '#fefefe',
    smoothyPinky: '#ffeeee',
    grey: '#acacac',
    pureGrey: '#989898',
    darkGrey: '#434343',
    convertInputGrey: '#ebf2f3',
    brownyGrey: '#8C8585',
    darkBrownyGrey: '#6d6666',
    black: isLight ? '#000' : '#fff',
    danger: '#FF5656',
    soullessRed: '#cc4b45',
    powerRed: '#e00606',
    darkRed: '#ff2424',
    powerOrange: '#DF4D2F',
    orange: '#f77715',
    modalButton: '#F7931A',
    golden: '#FFC400',
    soullessGold: '#E5C66D',
    warn: '#DEAB5E',
    success: '#00C286',
    green: '#00b45a',
    dark: '#1C292B',
    highBlue: '#00226e',
    soullessBlue: '#446086',
    white: '#ffff',
    containerBackground: isLight ? '#F8F9F9' : '#181818',
    lightGreen: '#D6FFF2',
    warnRed: '#F67373',
    lightBlue: '#25CAEB',
    errorStatusRed: '#d65d5d',
    greenGrass: '#5cc87a',
    grayLight: '#d5e1e3',
    orangeLight: '#0f00181c',
    orangeWarning: '#f77a22',
  },
  // Fonts: {
  //   first: 'IRANSansMobile',
  //   second: 'IRANSansMobile-Medium',
  //   third: 'IRANSansMobile-Light',
  //   heading: 'IRANSansMobile-Bold',
  //   input: 'IRANSansMobileFaNum',
  // },
};
